#!/bin/bash

python network_generator_for_50docs.py --json_file=Doc_52 --threshold=0.85 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_52 --threshold=0.85 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_52 --threshold=0.85 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_52 --threshold=0.90 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_52 --threshold=0.90 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_52 --threshold=0.90 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_52 --threshold=0.95 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_52 --threshold=0.95 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_52 --threshold=0.95 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.80 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.80 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.80 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.85 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.85 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.85 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.90 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.90 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.90 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.95 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.95 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_55 --threshold=0.95 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.80 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.80 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.80 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.85 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.85 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.85 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.90 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.90 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.90 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.95 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.95 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_57 --threshold=0.95 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.80 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.80 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.80 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.85 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.85 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.85 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.90 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.90 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.90 --numerical=0 --table2 --table3
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.95 --numerical=0 --table1 --table2
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.95 --numerical=0 --table1 --table3
python network_generator_for_50docs.py --json_file=Doc_69 --threshold=0.95 --numerical=0 --table2 --table3